CREATE TABLE [dbo].[SESSIONS](
	[SESSIONID] [nvarchar](50) NOT NULL,
	[APPLICATIONNAME] [nvarchar](255) NOT NULL,
	[CREATED] [datetime] NOT NULL,
	[EXPIRES] [datetime] NOT NULL,
	[LOCKDATE] [datetime] NOT NULL,
	[LOCKID] [numeric](18, 0) NOT NULL,
	[TIMEOUT] [numeric](18, 0) NOT NULL,
	[LOCKED] [bit] NOT NULL,
	[SESSIONITEMS] [text] NULL,
	[FLAGS] [int] NOT NULL,
 CONSTRAINT [PK_SESSIONS] PRIMARY KEY CLUSTERED 
(
	[SESSIONID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]